dist: xenial
addons:
  apt:
    sources:
    - sourceline: 'ppa:dns-oarc/dnscap-pr'
    update: true
    packages:
    - libpcap-dev
    - libldns-dev
    - libyaml-perl
    - zlib1g-dev
    - libssl-dev
    - libcryptopant-dev
  sonarcloud:
    organization: "dns-oarc"
    token:
      secure: "XouQDhoXhsoAOJuwc3DVKnuUhuwx/Ny3U4TQTG+DzzPyZVYH9gdcQ9Z/c4I5k7heEF9nlijbXPjz6wBg0XfSSVDnEuaD2SHZ23KEeshfCh3WBubS/7oGb8+fzSoM9YyxfHP+jBrST8XzsjoPN6F/R2FF32t4vwYBmfSlEqi18aI="
script:
  - ./autogen.sh
  - ./configure --enable-warn-all
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
